In [42]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import csv

In [43]:
#Create reference to CSV file
csv_path_people = "Resources/Traffic_Crashes_-_People.csv"

#Impor the CSV into a pandas DataFrame
df1 = pd.read_csv(csv_path_people)

In [44]:
#Create reference to CSV file for second file
csv_path_crashes = "Resources/Traffic_Crashes_-_Crashes.csv"

df2 = pd.read_csv(csv_path_crashes)

In [45]:
#Create reference to CSV file for 3rd file
csv_path_vehicles = "Resources/Traffic_Crashes_-_Vehicles.csv"

df3 = pd.read_csv(csv_path_vehicles)

In [46]:
df1 = df1[['RD_NO', 'PERSON_ID', 'PERSON_TYPE', 'VEHICLE_ID', 'CRASH_DATE',
       'SEAT_NO', 'CITY', 'STATE', 'ZIPCODE', 'SEX', 'AGE',
       'DRIVERS_LICENSE_STATE', 'DRIVERS_LICENSE_CLASS', 'SAFETY_EQUIPMENT',
       'AIRBAG_DEPLOYED', 'EJECTION', 'INJURY_CLASSIFICATION', 'HOSPITAL',
       'EMS_AGENCY', 'EMS_RUN_NO', 'DRIVER_ACTION', 'DRIVER_VISION',
       'PHYSICAL_CONDITION', 'PEDPEDAL_ACTION', 'PEDPEDAL_VISIBILITY',
       'PEDPEDAL_LOCATION', 'BAC_RESULT', 'BAC_RESULT VALUE',
       'CELL_PHONE_USE']]

In [47]:
df3 = df3[['RD_NO', 'CRASH_UNIT_ID', 'CRASH_DATE', 'UNIT_NO', 'UNIT_TYPE',
       'NUM_PASSENGERS', 'VEHICLE_ID', 'CMRC_VEH_I', 'MAKE', 'MODEL',
       'LIC_PLATE_STATE', 'VEHICLE_YEAR', 'VEHICLE_DEFECT', 'VEHICLE_TYPE',
       'VEHICLE_USE', 'TRAVEL_DIRECTION', 'MANEUVER', 'TOWED_I', 'FIRE_I',
       'OCCUPANT_CNT', 'EXCEED_SPEED_LIMIT_I', 'FIRST_CONTACT_POINT']]
df3

,RD_NO,CRASH_UNIT_ID,CRASH_DATE,UNIT_NO,UNIT_TYPE,NUM_PASSENGERS,VEHICLE_ID,CMRC_VEH_I,MAKE,MODEL,...,VEHICLE_DEFECT,VEHICLE_TYPE,VEHICLE_USE,TRAVEL_DIRECTION,MANEUVER,TOWED_I,FIRE_I,OCCUPANT_CNT,EXCEED_SPEED_LIMIT_I,FIRST_CONTACT_POINT
0,JB278428,394092,05/24/2018 04:45:00 PM,2,DRIVER,NaN,379191.0,NaN,DODGE,CHARGER,...,NONE,PASSENGER,PERSONAL,W,STRAIGHT AHEAD,NaN,NaN,1.0,NaN,FRONT-LEFT
1,JB278428,394093,05/24/2018 04:45:00 PM,1,PARKED,NaN,379180.0,NaN,PONTIAC,G6,...,NONE,UNKNOWN/NA,UNKNOWN/NA,W,PARKED,NaN,NaN,0.0,NaN,SIDE-LEFT
2,JB281663,396094,05/28/2018 12:30:00 AM,1,DRIVER,NaN,380981.0,NaN,VOLKSWAGEN,JETTA,...,UNKNOWN,PASSENGER,UNKNOWN/NA,W,PASSING/OVERTAKING,NaN,NaN,1.0,NaN,SIDE-RIGHT
3,JB281663,396095,05/28/2018 12:30:00 AM,2,DRIVER,1.0,380986.0,NaN,NISSAN,NISSAN MAXIMA,...,NONE,PASSENGER,RIDESHARE SERVICE,W,STRAIGHT AHEAD,NaN,NaN,2.0,NaN,SIDE-LEFT
4,JB283806,396943,05/29/2018 11:30:00 AM,1,DRIVER,NaN,381829.0,NaN,UNKNOWN,UNKNOWN,...,UNKNOWN,UNKNOWN/NA,UNKNOWN/NA,E,STRAIGHT AHEAD,NaN,NaN,1.0,NaN,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527447,JC123075,567026,01/19/2019 11:15:00 PM,2,DRIVER,NaN,540775.0,NaN,INFINITI,M35,...,NONE,PASSENGER,PERSONAL,S,STRAIGHT AHEAD,NaN,NaN,1.0,NaN,REAR-LEFT
527448,JC123021,567030,01/19/2019 09:40:00 PM,1,DRIVER,NaN,540768.0,NaN,"TOYOTA MOTOR COMPANY, LTD.",CAMRY,...,UNKNOWN,PASSENGER,PERSONAL,S,STRAIGHT AHEAD,NaN,NaN,1.0,NaN,FRONT
527449,JC123097,567031,01/19/2019 11:45:00 PM,1,DRIVER,NaN,540770.0,NaN,JEEP,PATRIOT,...,UNKNOWN,SPORT UTILITY VEHICLE (SUV),UNKNOWN/NA,N,STRAIGHT AHEAD,NaN,NaN,1.0,NaN,FRONT
527450,JC123097,567032,01/19/2019 11:45:00 PM,2,DRIVER,NaN,540772.0,NaN,CHEVROLET,MALIBU (CHEVELLE),...,UNKNOWN,PASSENGER,UNKNOWN/NA,N,STRAIGHT AHEAD,NaN,NaN,1.0,NaN,REAR
527451,JC123021,567033,01/19/2019 09:40:00 PM,2,PEDESTRIAN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Merge two DataFrames together based on data that they share
new_df1 = pd.merge(df1, df2, on="column to merge together on")